extends Sprite2D

@onready var texto: CanvasLayer = get_node("../Cuadro")

func _ready():
	if Global.room == 1:
		texto.encolar(">SI:nada")
		texto.encolar(">SD:retratoJhNervioso")
		texto.encolar("H1")
		texto.encolar("H2")
		texto.encolar(">SD:retratoEsclavo2")
		texto.encolar("H3")
		texto.encolar(">SI:retratoPj")
		texto.encolar(">VO")
		texto.encolar("H4")
		texto.encolar(">SD:retratoJh")
		texto.encolar("H5")
	elif Global.human == 2 and Global.jugado_h:
		texto.encolar(">SD:1retratoJhSonriente")
		texto.encolar("H6")
		texto.encolar("H7")
		texto.encolar(">CH")
		texto.encolar("H8")
		texto.encolar(">CH")
		texto.encolar(">SD:1retratoJh")
		texto.encolar("H9")
		texto.encolar("H10")
		texto.encolar(">SD:1retratoJhSonriente")
		texto.encolar("H11")
		await texto.esperar()
		Global.human += 1
		Global.room += 1
		Global.salida_h = true
	elif Global.room == 4:
		texto.encolar(">SI:retratoPj")
		texto.encolar(">SD:retratoJhEmocionado")
		texto.encolar("H12")
		texto.encolar(">SD:1retratoJh")
		texto.encolar("H13")
		texto.encolar(">CH")
		texto.encolar("H14")
		texto.encolar(">CH")
		texto.encolar(">SD:1retratoJhNervioso")
		texto.encolar("H15")
		texto.encolar("H16")
		texto.encolar(">CH")
		texto.encolar("H17")
		texto.encolar(">CH")
		texto.encolar(">SD:1retratoJh")
		texto.encolar("H18")
		texto.encolar(">CH")
		texto.encolar("H19")
		texto.encolar(">CH")
		texto.encolar(">SD:1retratoJhNervioso")
		texto.encolar("H20")
		texto.encolar("H21")
		texto.encolar(">SD:1retratoJhSonriente")
		texto.encolar("H22")
		texto.encolar("H23")
		texto.encolar(">SD:1retratoJh")
		texto.encolar("H24")
		texto.encolar("H25")
		texto.encolar(">SD:1retratoJhEmocionado")
		texto.encolar("H26")
		texto.encolar(">SD:1retratoJhSonriente")
		texto.encolar("H27")
		texto.encolar("H28")
		texto.encolar(">CH")
		texto.encolar("H29")
		texto.encolar(">CH")
		texto.encolar(">SD:1retratoJh")
		texto.encolar("H30")
		texto.encolar(">SD:1retratoJhSospechoso")
		texto.encolar("H31")
		texto.encolar(">VO")
		texto.encolar("H32")
		texto.encolar(">VN")
		texto.encolar(">CH")
		texto.encolar("H33")
		texto.encolar(">CH")
		texto.encolar(">SD:1retratoJhEmocionado")
		texto.encolar("H34")
		texto.encolar(">SD:1retratoJhNervioso")
		texto.encolar("H35")
		texto.encolar(">SD:1retratoJhSonriente")
		texto.encolar("H36")
		texto.encolar(">CH")
		texto.encolar("H37")
		texto.encolar(">CH")
		texto.encolar(">SD:1retratoJh")
		texto.encolar("H38")
		texto.encolar(">SD:1retratoJhSospechoso")
		texto.encolar("H39")
		texto.encolar("H40")
		texto.encolar(">SD:1retratoJhEmocionado")
		texto.encolar("H41")
		texto.encolar(">VO")
		texto.encolar("H42")
		Global.human += 1

func _input(event):
	if event is InputEventMouseButton and event.pressed and event.button_index == MOUSE_BUTTON_LEFT:
		if get_rect().has_point(to_local(event.position)) and !texto.estar_activo():
			texto.encolar(">SD:retratoJh")
			match Global.human:
				0:
					texto.encolar(">SD:retratoJh")
					texto.encolar(">SI:retratoPj")
					texto.encolar("H43")
					texto.encolar(">CH")
					texto.encolar("H44")
					texto.encolar("H45")
					texto.encolar(">CH")
					texto.encolar("H46")
					texto.encolar(">SD:1retratoJhSonriente")
					texto.encolar("H47")
					texto.encolar(">CH")
					texto.encolar("H48")
					texto.encolar("H49")
					texto.encolar("H50")
					texto.encolar(">CH")
					texto.encolar(">SD:1retratoJhNervioso")
					texto.encolar("H51")
					texto.encolar(">CH")
					texto.encolar("H52")
					texto.encolar(">CH")
					texto.encolar("H53")
					texto.encolar(">CH")
					texto.encolar("H54")
					texto.encolar(">CH")
					texto.encolar(">SD:1retratoJhSonriente")
					texto.encolar("H55")
					texto.encolar(">CH")
					texto.encolar("H56")
					texto.encolar("H57")
					texto.encolar("H58")
					texto.encolar("H59")
					texto.encolar(">VO")
					texto.encolar("H60")
					texto.encolar(">VN")
					texto.encolar(">CH")
					texto.encolar("H61")
					texto.encolar(">SD:1retratoJhSospechoso")
					texto.encolar("H62")
					texto.encolar(">CH")
					texto.encolar("H63")
					texto.encolar(">CH")
					texto.encolar(">SD:1retratoJhEmocionado")
					texto.encolar("H64")
					texto.encolar(">CH")
					texto.encolar("H65")
					texto.encolar(">CH")
					texto.encolar(">SD:1retratoJh")
					texto.encolar("H66")
					texto.encolar("H67")
					texto.encolar(">CH")
					texto.encolar("H68")
					texto.encolar(">CH")
					texto.encolar(">SD:1retratoJhSonriente")
					texto.encolar("H69")
					texto.encolar("H70")
					texto.encolar("H71")
					texto.encolar(">SD:1retratoJhSospechoso")
					texto.encolar("H72")
					texto.encolar("H73")
					texto.encolar("H74")
					texto.encolar(">SD:1retratoJhSonriente")
					texto.encolar("H75")
					await texto.esperar()
					Global.human += 1
					Global.room += 1
					Global.salida_h = true
				1:
					texto.encolar(">SD:retratoJhEmocionado")
					texto.encolar(">SI:retratoPj")
					texto.encolar("H76")
				2:
					texto.encolar(">SD:1retratoJhSonriente")
					texto.encolar("H77")
					texto.encolar(">SD:1retratoJhEmocionado")
					texto.encolar("H78")
					await texto.esperar()
					Global.jugado_h = true
					get_tree().change_scene_to_file("res://juego_human/MainMenu.tscn")
				3:
					texto.encolar("H79")
