extends Sprite2D

@onready var texto: CanvasLayer = get_node("../Cuadro")
var soyPrimer = false

func _input(event):
	if event is InputEventMouseButton and event.pressed and event.button_index == MOUSE_BUTTON_LEFT:
		if get_rect().has_point(to_local(event.position)) and !texto.estar_activo():
			texto.encolar(">SD:retratoEsclavo5")
			if Global.wl == 0:
				texto.encolar(">SI:retratoPj")
				texto.encolar(">CH")
				texto.encolar("WL28")
				texto.encolar("WL29")
				texto.encolar(">CH")
				texto.encolar("WL30")
				texto.encolar(">SD:retratoEsclavo6")
				texto.encolar("WL31")
				texto.encolar(">CH")
				texto.encolar("WL32")
				texto.encolar(">CH")
				texto.encolar(">SD:retratoJwlSorprendida")
				texto.encolar("WL33")
				texto.encolar(">SD:1retratoJwlContenta")
				texto.encolar("WL34")
				texto.encolar("WL35")
				texto.encolar(">SD:1retratoJwlConfiada")
				texto.encolar("WL36")
				texto.encolar(">CH")
				texto.encolar("WL37")
				texto.encolar(">CH")
				texto.encolar(">SD:1retratoJwlLlorando")
				texto.encolar("WL38")
				texto.encolar(">CH")
				texto.encolar(">VO")
				texto.encolar("WL39")
				texto.encolar(">VN")
				texto.encolar("WL40")
				texto.encolar(">CH")
				texto.encolar(">SD:1retratoJwlContenta")
				texto.encolar("WL41")
				texto.encolar(">SD:1retratoJwlConfiada")
				texto.encolar("WL42")
				texto.encolar(">SD:1retratoJwl")
				texto.encolar("WL43")
				Global.wl += 1
			elif Global.wl == 1:
				texto.encolar("WL44")
				texto.encolar("WL45")
				texto.encolar("WL46")
				texto.encolar("WL47")
				texto.encolar("WL48")
				texto.encolar(">CH")
				texto.encolar("WL49")
				texto.encolar(">CH")
				texto.encolar("WL50")
				texto.encolar("WL51")
				texto.encolar(">CH")
				texto.encolar("WL52")
				texto.encolar(">CH")
				texto.encolar("WL53")
				texto.encolar("WL54")
				texto.encolar(">CH")
				texto.encolar("WL55")
				texto.encolar(">CH")
				texto.encolar("WL56")
				texto.encolar("WL57")
				texto.encolar("WL58")
				texto.encolar("WL59")
				texto.encolar("WL60")
				Global.wl += 1
				soyPrimer = true
			elif (Global.wl == 2 or Global.wl == 3 or Global.wl == 4) and soyPrimer == true:
				texto.encolar("WL61")
				texto.encolar(">PR")
				texto.encolar(">MN")
				await texto.esperar()
				texto.encolar(">SI:retratoPj")
				if Global.resp == true:
					texto.encolar("WL62")
					texto.encolar("WL63")
					texto.encolar("WL64")
					texto.encolar("WL65")
					texto.encolar("WL66")
					texto.encolar("WL67")
					texto.encolar("WL68")
				else:
					texto.encolar("WL69")
			elif Global.wl == 2 and soyPrimer == false:
				texto.encolar("WL70")
				texto.encolar("WL71")
				texto.encolar("WL72")
				texto.encolar("WL73")
				texto.encolar("WL74")
				texto.encolar("WL75")
				texto.encolar(tr("ESQ3"))
				texto.encolar(">CH")
				texto.encolar("WL76")
				texto.encolar(">CH")
				texto.encolar("WL77")
				Global.wl += 1
			elif (Global.wl == 3 or Global.wl == 4) and soyPrimer == false:
				texto.encolar("WL78")
				texto.encolar(">PR")
				texto.encolar(">MN")
				await texto.esperar()
				if Global.resp == true:
					texto.encolar("WL79")
					texto.encolar("WL80")
					texto.encolar("WL81")
					texto.encolar("WL82")
				else:
					texto.encolar("WL83")
