extends Sprite2D
@onready var texto: CanvasLayer = get_node("../Cuadro")

func _ready():
	if Global.wiki == 0:
		texto.encolar(">VO")
		texto.encolar("W1")
		texto.encolar(">CH")
		texto.encolar(">VN")
		texto.encolar("W2")
		texto.encolar(">SD:retratoJw")
		texto.encolar(">CH")
		texto.encolar("W3")
		texto.encolar("W4")
		texto.encolar(">CH")
		texto.encolar("W5")
		texto.encolar(">CH")
		texto.encolar(">SD:1retratoJwCalmado")
		texto.encolar("W6")
		texto.encolar(">CH")
		texto.encolar(">SD:1retratoJw")
		texto.encolar("W7")
		texto.encolar("W8")
		texto.encolar(">CH")
		texto.encolar("W9")
		texto.encolar(">SD:1retratoJwCalmado")
		texto.encolar("W10")
		texto.encolar(">CH")
		texto.encolar("W11")
		texto.encolar(">CH")
		texto.encolar(">SD:1retratoJwContento")
		texto.encolar("W12")
		texto.encolar(">CH")
		texto.encolar("W13")
		texto.encolar("W14")
		texto.encolar(">CH")
		texto.encolar(">SD:1retratoJwShock")
		texto.encolar("W15")
		texto.encolar(">CH")
		texto.encolar("W16")
		texto.encolar(">VO")
		texto.encolar("W17")
		texto.encolar(">CH")
		texto.encolar(">VN")
		texto.encolar(">SD:1retratoJwNervios")
		texto.encolar("W18")
		texto.encolar("W19")
		texto.encolar(">SD:1retratoJwShock")
		texto.encolar("W20")
		texto.encolar(">SD:1retratoJwNervios")
		texto.encolar(">SI:retratoEsclavo9")
		texto.encolar(">CH")
		texto.encolar("W21")
		texto.encolar(">SI:retratoEsclavo10")
		texto.encolar("W22")
		texto.encolar(">SI:retratoPj")
		texto.encolar("W23")
	elif Global.wiki == 2 and Global.jugado_w:
		texto.encolar(">SD:1retratoJwCalmado")
		texto.encolar("W24")
		texto.encolar(">SD:1retratoJwContento")
		texto.encolar("W25")
		await texto.esperar()
		Global.jefes_visible = true
		texto.encolar(">SD:retratoJwlLlorando")
		texto.encolar("W26")
		texto.encolar(">SD:retratoJdlSonriente")
		texto.encolar("W27")
		texto.encolar(">SD:retratoJrSorprendida")
		texto.encolar("W28")
		texto.encolar(">SD:1retratoJr")
		texto.encolar("W29")
		texto.encolar(">CH")
		texto.encolar("W30")
		texto.encolar("W31")
		texto.encolar(">CH")
		texto.encolar(">SD:retratoJhSospechoso")
		texto.encolar("W32")
		texto.encolar(">SD:1retratoJhSonriente")
		texto.encolar("W33")
		texto.encolar(">SD:retratoJwContento")
		texto.encolar("W34")
		await texto.esperar()
		Global.salida_wiki = true
		Global.wiki += 1
		Global.room += 1
func _input(event):
	if event is InputEventMouseButton and event.pressed and event.button_index == MOUSE_BUTTON_LEFT:
		if get_rect().has_point(to_local(event.position)) and !texto.estar_activo():
			texto.encolar(">SD:retratoJw")
			if Global.wiki < 2:
				texto.encolar(">SD:1retratoJwNervios")
				texto.encolar("W35")
				texto.encolar("W36")
			elif Global.wiki == 2:
				texto.encolar(">SD:1retratoJwShock")
				texto.encolar("W37")
				texto.encolar(">SD:1retratoJwNervios")
				texto.encolar("W38")
				texto.encolar("W39")
				texto.encolar(">PR")
				texto.encolar(">MN")
				await texto.esperar()
				if Global.resp == false:
					texto.encolar(">SD:1retratoJwShock")
					texto.encolar("W40")
					texto.encolar(">SD:1retratoJwNervios")
					texto.encolar("W41")
					texto.encolar("W42")
				else:
					Global.jugado_w = true
					get_tree().change_scene_to_file("res://juego_wiki2/minijuego.tscn")
			elif Global.wiki == 3:
				texto.encolar(">SD:1retratoJwContento")
				texto.encolar("W43")
				texto.encolar(">SD:1retratoJwCalmado")
				texto.encolar("W44")
